[build-system]
requires = ["setuptools>=61.2.0", "wheel", "setuptools_scm[toml]>=3.4.3"]
build-backend = "setuptools.build_meta"

[project]
name = "adb_shell"
authors = [{name = "Jeff Irion", email = "jefflirion@users.noreply.github.com"}]
description = "A Python implementation of ADB with shell and FileSync functionality."
license = {text = "Apache-2.0"}
keywords = ["adb", "android"]
readme = "README.rst"
classifiers = [
    "Operating System :: OS Independent",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 2",
]
urls = {Homepage = "https://github.com/JeffLIrion/adb_shell"}
dependencies = ["cryptography", "pyasn1", "rsa"]
dynamic = ["version"]

[project.optional-dependencies]
usb = ["libusb1>=1.0.16"]
async = ["aiofiles>=0.4.0"]
testing = ["pycryptodome", "libusb1>=1.0.16"]

[tool.setuptools]
packages = [
    "adb_shell",
    "adb_shell.auth",
    "adb_shell.transport",
]

[tool.setuptools_scm]
write_to = "adb_shell/version.py"
write_to_template = "'''Generated by setuptools_scm'''\n__version__ = '{version}'\n"

[tool.distutils.bdist_wheel]
universal = 1
